version: "3.7"

services:
  mongo:
    image: mongo
    container_name: retro-mongo
    ports: 
      - "27018:27017"
    networks: 
      - dev
    privileged: true

  backend:
    build: ./backend/
    image: retro-backend
    container_name: retro-backend
    volumes:
        - ./backend:/app
    ports:
      - "3001:3001"
    networks:
      - dev
    restart: always
    environment:
      - NODE_ENV=DEVELOPMENT

  frontend:
    build: ./frontend/
    image: retro-frontend
    container_name: retro-frontend
    volumes:
        - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - dev
    restart: always
    environment:
      - NODE_ENV=DEVELOPMENT
      - DEV_ENV=DOCKER
      - DOCKER_HOST_IP=$DOCKER_HOST_IP

networks:
  dev:
    driver: bridge
