version: 2
jobs:
  build:
    working_directory: ~/retro
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "backend/package.json" }}-{{ checksum "frontend/package.json" }}

      - run: 
          name: Setup Backend Dependencies
          command: cd backend && yarn install && cd ..
      
      - run:
          name: Setup Frontend Dependencies
          command: cd frontend && yarn install && cd ..

      - save_cache:
          paths:
            - backend/node_modules
            - frontend/node_modules
          key: dependency-cache-{{ checksum "backend/package.json" }}-{{ checksum "frontend/package.json" }}

      - run:
          name: Check formatting on backend
          command: cd backend && yarn format:check && cd ..

      - run:
          name: Check formatting on frontend
          command: cd frontend && yarn format:check && cd ..
      
      - run:
          name: Run ESLint on backend
          command: cd backend && yarn lint && cd ..

      - run:
          name: Run ESLint on frontend
          command: cd frontend && yarn lint && cd ..

      - run:
          name: Run tests on backend
          command: cd backend && yarn test && cd ..
      
      - run:
          name: Run tests on frontend
          command: cd frontend && yarn test && cd ..